---
title: "Historical Records for Hummingbirds and Plants"
author: "Ben Weinstein"
date: "Thursday, January 08, 2015"
output:
  html_document:
    theme: spacelab
---


```{r,echo=FALSE,message=FALSE,warning=FALSE}
library(dplyr)
library(reshape2)
library(ggplot2)
library(spocc)
library(knitr)
library(spline)
library(chron)
opts_chunk$set(message=FALSE,warning=FALSE,fig.width=13,echo=FALSE,cache=TRUE,cache.path = 'gbif_cache/', fig.path='figuregbif/')
```

#Aim


#Approach

#Plant Records

Search for dominant hummigbird pollinated plants


### Search for occurrence IDs in GBIF
```{r}
out <- occ(query="Penstemon",limit=10000,from=c("gbif","inat","bison"))
df<-occ2df(out)

df$year<-years(df$date)
ydat<-df %>% group_by(name,year) %>% summarize(n=n()) %>% filter(!is.na(year)) + scale_x_chron() 

ggplot(ydat,aes(x=as.numeric(as.character(year)),y=n,col=name)) + geom_point() + geom_smooth(aes(group=name),method="glm",family="quasipoisson", formula = y ~ ns(x, 3)) + ggtitle("Records over time") + xlab("Year")

df$month<-months(df$date)
mdat<-df %>% group_by(name,month) %>% summarize(n=n()) %>% filter(!is.na(month))
mdat$month<-factor(mdat$month,levels=month.name)


ggplot(mdat,aes(x=month,y=n)) + geom_point() + geom_smooth(aes(group=1))
```

##Get all records with this genus key
```{r,eval=F}

```

#Penstemon GBIF example
```{r}
#optionally read in data 
dat<-read.csv("Data/Penstemon.csv")

#missing year stamp
missing<-dat[is.na(dat$year),]
```

#Records over time

```{r}
s<-group_by(dat,year) %>% summarize(n=n())
s$Time<-strptime(paste(s$month,1,s$year,sep="/"),format="%m/%d/%Y")

ggplot(data=dat,aes(x=year))  + geom_histogram() + theme_bw() + labs(x="Year",y="Records") + geom_vline(xintercept=1955)
```

##Where do these records come from?

```{r}
datplot<-dat
datplot$name<-"Penstemon"
datplot$species<-"Penstemon"
gbifmap(input=datplot,mapdatabase="usa")
```

#Flowering Duration for each species, across time
Assuming that the vast majority of plants are colleced in flower
```{r,fig.height=30}
p
#just get the most common species for the moment, atleast 50 records
keep<-names(which(table(dat$species)>500))
dplot<-dat %>% filter(species %in% keep) %>% mutate(minm=mean(month,na.rm=T)) %>% arrange(minm) %>% mutate(Month.abb=factor(month.abb[month],levels=month.abb)) %>% select(species,month,Month.abb) %>% filter(!is.na(month))

p<-ggplot(dplot,aes(x=species,y=month)) + geom_violin(fill="black") + theme_bw() + coord_flip() + scale_y_discrete(labels=month.abb)

```

